[app]
name = "anime-model-server-rs"

[build]
commands = ["docker build -f ../Dockerfile.model_server_rs -t anime-model-server-rs:latest .."]
image = "anime-model-server-rs:latest"

[deploy]
health = { url = "http://localhost:5708/health" }

[deploy.run]
net = "host"
env = { PORT = "5708", METRICS_PORT = "5709", PRECISION = "bf16" }
